apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: mcp-on-cloudrun
  annotations:
    run.googleapis.com/binary-authorization: default #TODO: Add config
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: '1'
        autoscaling.knative.dev/maxScale: '50'
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      containers:
      - image: us-central1-docker.pkg.dev/gmao-test-project/gmao-repo/mcp-on-cloudrun:latest